name: strict-tests

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  strict-tests:
    runs-on: "ubuntu-latest"
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        php:
          - 8.1
          - 8.2
          - 8.3
        phpunit:
          - "~10.1.0"
          - "~10.2.0"
          - "~10.3.0"
          - "~10.4.0"
          - "~10.5.0"
          - "10.5.4"
        experimental:
          - false

    name: PHP${{ matrix.php }} / PHPUnit:${{ matrix.phpunit }} ⬆️

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, intl, fileinfo, :php-psr
          coverage: none

      - name: Install dependencies
        uses: "ramsey/composer-install@v3"
        with:
          dependency-versions: "highest"
          composer-options: "--prefer-dist --no-cache --with=phpunit/phpunit:${{ matrix.phpunit }}"

      - name: Installed dependencies
        run: |
          composer show -D

      - name: Execute tests
        run: vendor/bin/phpunit --fail-on-warning --fail-on-deprecation --fail-on-notice